//! The provisioning rules, described (plan I1): the decision points `Provisioner::provision_round`,
//! the install task, and the activation hook pass through — the stem pilot (I5) instruments these.
//! Metadata only; the mechanism is in `provisioner.rs`, `runtime.rs` and `activation.rs`.
//!
//! Relationships here are hypotheses from reading the code (plan §6); the trace is what will show them.
//! Eleven are `Instrumented` by the pilot (I5, `Provisioner::with_decision_trace`) — activation and probe
//! since the install token and the trace travel into the runtime hook (`ActivationCtx`, 2026-10-03);
//! provenance and loadable (no typed reason at the decision point today), advertise and withdraw (under the
//! hosted lock) stay catalogue-only.

use mycelium::rule::{Guard, Input, Outcome, OutcomeKind::*, Responsibility::*, RuleDescriptor, TracePolicy::*};

const DEMAND: Input = Input { source: "capabilities().demand(filter) — `demand/` and `cap/` as gossiped", scope: "the fleet as this node sees it", freshness: "as gossiped; may be stale or partial" };
const HOSTED: Input = Input { source: "Provisioner::hosted (lock-order row 21)", scope: "this node", freshness: "local, atomic" };
const CATALOG: Input = Input { source: "the signed catalogue (`installable/` as gossiped, or the library manifest)", scope: "the fleet as this node sees it", freshness: "as gossiped; verified on read" };
const UNIT: Input = Input { source: "the unit file (`[hosts]`, `[[presence]]`, `[[activation]]`)", scope: "this node", freshness: "read at start" };
const PROBE: Input = Input { source: "ResourceProbe (memory, disk headroom)", scope: "this node", freshness: "sampled at the decision" };
const LEDGER: Input = Input { source: "InstallRights::ledger (lock-order row 37)", scope: "this node's allocation", freshness: "local; the head is published after" };

pub static RULES: &[RuleDescriptor] = &[
    RuleDescriptor {
        id: "prov.health_pass", revision: 1, subsystem: "mycelium-wasm-host::provisioner", responsibilities: &[Response],
        trigger: "every provisioning round, first",
        inputs: &[HOSTED, Input { source: "each live install's `probe()` (file present, and the activation health flag)", scope: "this node", freshness: "sampled under row 21" }],
        outcomes: &[Outcome { kind: Action, reasons: &["probe_failed"] }, Outcome { kind: NoAction, reasons: &["all_healthy"] }],
        effects: &["withdraw(): the capability's advertisement is tombstoned and the install removed", "`mycelium_artifact_probe_withdrawals_total`"],
        guards: &[Guard::Health], may_trigger: &["prov.presence_floor", "prov.demand_response"], may_inhibit: &[], depends_on: &["prov.probe"],
        symbol: "provisioner::Provisioner::provision_round", docs: "docs/operations/capability-lifecycle.md",
        tests: &["a_declared_activation_runs_after_placement_and_its_probe_gates_the_capability", "the_stem_fleet_fills_a_presence_floor_and_reheals"],
        trace: Instrumented,
        summary: "A live install whose probe fails this round is withdrawn; restart ≡ provisioning brings it back.",
    },
    RuleDescriptor {
        id: "prov.promotion", revision: 1, subsystem: "mycelium-wasm-host::provisioner", responsibilities: &[Response],
        trigger: "every provisioning round, after the health pass",
        inputs: &[HOSTED, CATALOG, UNIT],
        outcomes: &[Outcome { kind: Action, reasons: &["accepted_withdraw_shadow"] }, Outcome { kind: NoAction, reasons: &["still_proposed", "no_shadow_installs"] }],
        effects: &["withdraw() of the `{name}.shadow` install once the entry is accepted, so the live rule reinstalls it"],
        guards: &[Guard::Provenance], may_trigger: &["prov.demand_response"], may_inhibit: &[], depends_on: &["prov.loadable"],
        symbol: "provisioner::Provisioner::provision_round", docs: "docs/guide/16-guardrails.md",
        tests: &["a_proposed_entry_loads_only_into_the_shadow_lane_until_a_listed_reviewer_accepts_it"], trace: Instrumented,
        summary: "A shadow install whose entry a listed reviewer has since accepted is withdrawn from the shadow lane (D20).",
    },
    RuleDescriptor {
        id: "prov.demand_response", revision: 1, subsystem: "mycelium-wasm-host::provisioner", responsibilities: &[Response],
        trigger: "every provisioning round, per catalogue entry this node could host",
        inputs: &[DEMAND, HOSTED, CATALOG, UNIT],
        outcomes: &[
            Outcome { kind: Action, reasons: &["unmet_demand_live", "unmet_demand_shadow"] },
            Outcome { kind: Deferral, reasons: &["self_election_declined", "already_started_this_round"] },
            Outcome { kind: Refusal, reasons: &["already_hosted", "provenance_rejected", "ineligible", "rights_refused"] },
            Outcome { kind: NoAction, reasons: &["no_demand", "provider_present"] },
        ],
        effects: &["start_install (live) or the shadow lane", "`mycelium_artifact_shadow_installs_total`"],
        guards: &[Guard::Provenance, Guard::ResourceBudget, Guard::Authority],
        may_trigger: &["prov.install"], may_inhibit: &[], depends_on: &["prov.provenance", "prov.loadable", "prov.eligible", "prov.self_election", "prov.rights_admission"],
        symbol: "provisioner::Provisioner::provision_round", docs: "docs/operations/capability-lifecycle.md",
        tests: &["a_hosting_stem_re_serves_its_verified_cache_to_a_late_joiner", "a_proposed_entry_loads_only_into_the_shadow_lane_until_a_listed_reviewer_accepts_it"],
        trace: Instrumented,
        summary: "A requirement with demanding nodes and no provider, as this node sees it, makes this node a candidate installer; an observed unmet requirement is not an instruction to install.",
    },
    RuleDescriptor {
        id: "prov.presence_floor", revision: 1, subsystem: "mycelium-wasm-host::provisioner", responsibilities: &[Response],
        trigger: "every provisioning round, per `[[presence]]` declaration",
        inputs: &[DEMAND, HOSTED, CATALOG, UNIT],
        outcomes: &[
            Outcome { kind: Action, reasons: &["below_floor"] },
            Outcome { kind: Deferral, reasons: &["self_election_declined"] },
            Outcome { kind: Refusal, reasons: &["already_hosted", "provenance_rejected", "ineligible", "no_loadable_candidate"] },
            Outcome { kind: NoAction, reasons: &["floor_met"] },
        ],
        effects: &["start_install of the smallest loadable candidate"],
        guards: &[Guard::Provenance, Guard::ResourceBudget], may_trigger: &["prov.install"], may_inhibit: &[],
        depends_on: &["prov.provenance", "prov.loadable", "prov.eligible", "prov.self_election"],
        symbol: "provisioner::Provisioner::provision_round", docs: "docs/reference/unit-file.md",
        tests: &["the_stem_fleet_fills_a_presence_floor_and_reheals"], trace: Instrumented,
        summary: "Fewer live providers than the declared floor, as this node sees it, makes this node a candidate installer of the cheapest loadable entry.",
    },
    RuleDescriptor {
        id: "prov.shed", revision: 2, subsystem: "mycelium-wasm-host::provisioner", responsibilities: &[Response],
        trigger: "every provisioning round, per `[[presence]]` declaration with a ceiling",
        inputs: &[DEMAND, HOSTED, Input { source: "`prov-shed/{ns}:{name}:{hash}` advertisements — which providers will act on this band's shed", scope: "the fleet as this node sees it", freshness: "as gossiped; may be stale or partial" }],
        outcomes: &[Outcome { kind: Action, reasons: &["above_ceiling"] }, Outcome { kind: NoAction, reasons: &["within_ceiling", "not_hosting", "ranked_within_ceiling"] }],
        effects: &["withdraw() of this node's install"], guards: &[], may_trigger: &[], may_inhibit: &["prov.presence_floor"], depends_on: &[],
        symbol: "provisioner::Provisioner::provision_round", docs: "docs/reference/unit-file.md",
        tests: &["the_stem_fleet_fills_a_presence_floor_and_reheals", "exactly_the_surplus_above_a_ceiling_withdraws", "a_provider_that_does_not_shed_does_not_hold_the_band_above_its_ceiling", "a_wrong_view_costs_at_most_its_wrong_entries_and_never_cascades", "bands_that_differ_only_in_attributes_or_ceiling_have_different_shed_names", "a_herd_of_new_installs_lands_on_the_ceiling", "a_partition_heals_without_emptying_the_band"], trace: Instrumented,
        summary: "More live providers than the declared ceiling withdraws the hosts ranked beyond it by the band's rendezvous order, among the providers that advertise they will act on it (`prov-shed`; rev 2; rev 1 drew per host, and every host could withdraw at once).",
    },
    RuleDescriptor {
        id: "prov.provenance", revision: 1, subsystem: "mycelium-wasm-host::provisioner", responsibilities: &[Authority],
        trigger: "a candidate entry, before any other check",
        inputs: &[CATALOG, Input { source: "`[hosts].trusted_publishers`", scope: "this node", freshness: "read at start" }],
        outcomes: &[Outcome { kind: Action, reasons: &["signed_by_trusted_publisher", "no_trust_list_configured"] }, Outcome { kind: Refusal, reasons: &["signature_invalid", "publisher_untrusted"] }],
        effects: &[], guards: &[Guard::Provenance], may_trigger: &[], may_inhibit: &["prov.demand_response", "prov.presence_floor"], depends_on: &[],
        symbol: "provisioner::Provisioner::provenance_ok", docs: "docs/operations/artifacts.md",
        tests: &["a_proposal_round_trips_as_v2_and_its_signature_is_its_own", "the_stem_fleet_fills_a_presence_floor_and_reheals"], trace: CatalogueOnly,
        summary: "An entry is a candidate only if a trusted publisher signed it; an empty trust list trusts everything, which the report says.",
    },
    RuleDescriptor {
        id: "prov.loadable", revision: 1, subsystem: "mycelium-wasm-host::catalog", responsibilities: &[Authority],
        trigger: "a candidate entry",
        inputs: &[CATALOG, Input { source: "`[hosts].trusted_reviewers`", scope: "this node", freshness: "read at start" }],
        outcomes: &[Outcome { kind: Action, reasons: &["accepted", "not_a_proposal"] }, Outcome { kind: Refusal, reasons: &["proposed_unaccepted"] }],
        effects: &[], guards: &[Guard::Authority], may_trigger: &[], may_inhibit: &[], depends_on: &["prov.provenance"],
        symbol: "catalog::InstallableEntry::is_loadable", docs: "docs/guide/16-guardrails.md",
        tests: &["a_proposed_entry_loads_only_into_the_shadow_lane_until_a_listed_reviewer_accepts_it"], trace: CatalogueOnly,
        summary: "A proposed entry loads live only once a listed reviewer has accepted it; until then it may load into the shadow lane only (D20).",
    },
    RuleDescriptor {
        id: "prov.eligible", revision: 1, subsystem: "mycelium-wasm-host::provisioner", responsibilities: &[Response],
        trigger: "a candidate entry that passed provenance",
        inputs: &[CATALOG, UNIT, PROBE, HOSTED],
        outcomes: &[Outcome { kind: Action, reasons: &["eligible"] }, Outcome { kind: Refusal, reasons: &["no_runtime", "budget", "memory", "disk"] }],
        effects: &["`mycelium_artifact_ineligible_skips_total{reason}`"], guards: &[Guard::ResourceBudget], may_trigger: &[], may_inhibit: &["prov.demand_response", "prov.presence_floor"], depends_on: &["prov.provenance"],
        symbol: "provisioner::Provisioner::eligible", docs: "docs/operations/capability-lifecycle.md",
        tests: &["the_stem_fleet_fills_a_presence_floor_and_reheals"], trace: Instrumented,
        summary: "This node hosts the entry's kind, has install budget left, and has memory and disk headroom for it. The check has side effects (counters) and is never re-evaluated for a record.",
    },
    RuleDescriptor {
        id: "prov.rights_admission", revision: 1, subsystem: "mycelium-wasm-host::provisioner", responsibilities: &[Authority],
        trigger: "an install about to start, when install rights are configured",
        inputs: &[LEDGER, HOSTED],
        outcomes: &[Outcome { kind: Action, reasons: &["admitted"] }, Outcome { kind: Refusal, reasons: &["allocation_exhausted"] }, Outcome { kind: NoAction, reasons: &["would_refuse_shadow_mode", "no_rights_configured"] }],
        effects: &["the ledger's admit record and published head", "`mycelium_artifact_installs_refused_by_rights_total`"],
        guards: &[Guard::Authority, Guard::ResourceBudget], may_trigger: &[], may_inhibit: &["prov.install"], depends_on: &[],
        symbol: "provisioner::Provisioner::admit_install", docs: "docs/guide/22-stability-and-control.md",
        tests: &["an_install_is_refused_and_recorded_when_the_node_holds_no_rights"], trace: Instrumented,
        summary: "An install takes a right from this node's allocation first; under the enforcing profile a node with none left refuses, and records that it did.",
    },
    RuleDescriptor {
        id: "prov.self_election", revision: 1, subsystem: "mycelium-wasm-host::provisioner", responsibilities: &[Response],
        trigger: "a candidate that passed every other check",
        inputs: &[Input { source: "`StemOptions::self_elect_p` and one draw from the `select` RNG stream (through the seam since 2026-10-03)", scope: "this node", freshness: "the draw" }],
        outcomes: &[Outcome { kind: Action, reasons: &["elected"] }, Outcome { kind: Deferral, reasons: &["declined"] }],
        effects: &[], guards: &[Guard::Cooldown], may_trigger: &[], may_inhibit: &["prov.demand_response", "prov.presence_floor"], depends_on: &[],
        symbol: "provisioner::Provisioner::self_elects", docs: "docs/operations/capability-lifecycle.md",
        tests: &["the_stem_fleet_fills_a_presence_floor_and_reheals"], trace: Instrumented,
        summary: "Herd damping: a candidate acts this round with probability p, drawn after the guards so a decline costs nothing. Replay-covered since the draw went through the seam.",
    },
    RuleDescriptor {
        id: "prov.install", revision: 1, subsystem: "mycelium-wasm-host::provisioner", responsibilities: &[Response],
        trigger: "an admitted install",
        inputs: &[CATALOG, HOSTED, Input { source: "the artifact bytes, by content address (library, mesh, or store)", scope: "wherever the source reaches", freshness: "verified against the entry's hash" }],
        outcomes: &[Outcome { kind: Action, reasons: &["completed"] }, Outcome { kind: Refusal, reasons: &["fetch", "verify", "place", "activation", "resources", "host"] }, Outcome { kind: NoAction, reasons: &["superseded"] }],
        effects: &["`HostedState::Installing` → `Live` under the install token", "the `{ns}/loading` tier while bytes arrive", "`mycelium_artifact_installs_started_total`, `_completed_total`, `_failed_total{stage}`"],
        guards: &[Guard::Provenance], may_trigger: &["prov.activation", "prov.advertise"], may_inhibit: &[], depends_on: &["prov.rights_admission"],
        symbol: "provisioner::Provisioner::start_install_as", docs: "docs/operations/capability-lifecycle.md",
        tests: &["the_stem_fleet_fills_a_presence_floor_and_reheals", "an_installed_tool_component_is_bridged_as_an_mcp_tool"], trace: Instrumented,
        summary: "Fetch, verify, place and host the artifact under an install token; a superseded token tears its install down rather than advertising it.",
    },
    RuleDescriptor {
        id: "prov.activation", revision: 1, subsystem: "mycelium-wasm-host::activation", responsibilities: &[Response],
        trigger: "a placed blob whose capability a `[[activation]]` names",
        inputs: &[UNIT, Input { source: "the placed path, and `artifact:<hex>` references rendered to placed paths", scope: "this node", freshness: "local" }],
        outcomes: &[Outcome { kind: Action, reasons: &["activated"] }, Outcome { kind: Refusal, reasons: &["command_failed", "command_timed_out", "reference_not_placed_yet", "render_failed"] }, Outcome { kind: NoAction, reasons: &["no_declaration"] }],
        effects: &["the operator's command, run with the stem's privileges — not a sandbox"],
        guards: &[Guard::Other], may_trigger: &["prov.probe"], may_inhibit: &[], depends_on: &["prov.install"],
        symbol: "activation::hook", docs: "docs/reference/unit-file.md",
        tests: &["a_declared_activation_runs_after_placement_and_its_probe_gates_the_capability", "an_activation_resolves_artifact_references_to_placed_paths", "a_verbose_command_that_succeeds_is_not_reported_as_a_timeout"],
        trace: Instrumented,
        summary: "After placement the declared command hands the blob to its local runtime; a failure is an install failure at stage `activation`, retried next round.",
    },
    RuleDescriptor {
        id: "prov.probe", revision: 2, subsystem: "mycelium-wasm-host::activation", responsibilities: &[Response],
        trigger: "after activation, and on every re-probe tick",
        inputs: &[UNIT, Input { source: "the declared probe argv's exit status", scope: "this node", freshness: "sampled" }],
        outcomes: &[Outcome { kind: Action, reasons: &["healthy"] }, Outcome { kind: Refusal, reasons: &["initial_probe_failed", "probe_failed"] }, Outcome { kind: NoAction, reasons: &["no_probe_declared"] }],
        effects: &["the install's health flag, which `prov.health_pass` reads"],
        guards: &[Guard::Health], may_trigger: &["prov.health_pass"], may_inhibit: &["prov.advertise"], depends_on: &["prov.activation"],
        symbol: "activation::hook / activation::spawn_reprobe", docs: "docs/reference/unit-file.md",
        tests: &["a_failing_initial_probe_is_an_activation_error", "a_declared_activation_runs_after_placement_and_its_probe_gates_the_capability"], trace: Instrumented,
        summary: "The probe gates the capability: a failing initial probe is an activation error (nothing advertised); a later failure flips the health flag the next health pass withdraws on. Recorded under the install's token; a re-probe records only a change of verdict.",
    },
    RuleDescriptor {
        id: "prov.advertise", revision: 1, subsystem: "mycelium-wasm-host::provisioner", responsibilities: &[Propagation],
        trigger: "an install that completed, before its state swaps to `Live`",
        inputs: &[CATALOG],
        outcomes: &[Outcome { kind: Action, reasons: &["advertised"] }],
        effects: &["`cap/` advertisement of the entry's capability, held by the install; tombstoned on withdrawal"],
        guards: &[], may_trigger: &["prov.demand_response"], may_inhibit: &[], depends_on: &["prov.install", "prov.probe"],
        symbol: "provisioner::Provisioner::start_install_as", docs: "docs/guide/02-capabilities.md",
        tests: &["the_stem_fleet_fills_a_presence_floor_and_reheals"], trace: CatalogueOnly,
        summary: "A completed install advertises its capability to the mesh; the advertisement's lifetime is the install's.",
    },
    RuleDescriptor {
        id: "prov.withdraw", revision: 1, subsystem: "mycelium-wasm-host::provisioner", responsibilities: &[Propagation, Response],
        trigger: "a health-pass failure, a promotion, a shed, or a superseded install",
        inputs: &[HOSTED],
        outcomes: &[Outcome { kind: Action, reasons: &["withdrawn"] }, Outcome { kind: NoAction, reasons: &["not_hosted"] }],
        effects: &["the install removed under row 21, then uninstalled outside it; the advertisement tombstoned"],
        guards: &[], may_trigger: &["prov.presence_floor"], may_inhibit: &[], depends_on: &[],
        symbol: "provisioner::Provisioner::withdraw", docs: "docs/operations/capability-lifecycle.md",
        tests: &["a_declared_activation_runs_after_placement_and_its_probe_gates_the_capability"], trace: CatalogueOnly,
        summary: "Withdrawal removes the install and tombstones its advertisement; restart ≡ provisioning is how it comes back.",
    },
];
