#!/usr/bin/env bash
# The wiki mutation-fence check — v3 contracts axis, item 5.
#
# WHY IT EXISTS
#   §6.3 of `docs/plans/v3-contracts-axis.md` claims **"every mutation path protected"** — apply,
#   bulk ingest, erase, bootstrap, imports, admin, raw credentials. §5 of
#   `docs/design/scoped-mandates.md` says where that protection lives: the mandate check is inside
#   the canonical store's *own atomic boundary* — one `git update-ref --stdin` transaction locally,
#   `--atomic` plus `--force-with-lease` on the mandate ref remotely.
#
#   A claim of the form "every path" decays the moment someone adds a path. `GitStore` already
#   funnels its content writes through one chokepoint (`commit_files`), which is exactly what makes
#   the claim true today — and exactly what a future refactor can undo without anyone noticing,
#   because nothing fails when a new `update-ref` appears beside the fenced one.
#
# WHAT IT COMPARES
#   Per file: the number of git **ref-moving** sites, and the number of `mandate_fence::` call
#   sites, against `scripts/wiki-mutation-fence-baseline.txt`. A file that gains a ref-moving site
#   without gaining a fence site **fails** — a new write path has to be either fenced or admitted by
#   editing the record. Losing a fence site fails too: that is the fence being removed.
#
#   It also asserts positively that both fence entry points are still reached — a baseline of
#   matching counts would otherwise be satisfied by deleting the fence and the write together.
#
# THE TWO UNFENCED SITES, NAMED RATHER THAN GLOSSED
#   `refresh` adopts the remote head as local truth (`update-ref <ref> <remote_sha>`). It creates no
#   content; it takes what the remote's pre-receive hook already fenced. Not a mutation path in the
#   mandate sense.
#
#   `publish`'s splice retry CAS-moves the **local** ref to a two-parent commit that re-parents our
#   already-fenced scope files onto theirs. The subsequent push *is* fenced, so the remote is
#   protected — but the local ref moves **without re-verifying the mandate**, so a revocation that
#   lands mid-retry-loop is not observed locally until the push fails. That is a real, narrow gap,
#   recorded in `docs/design/scoped-mandates.md` §7.2 rather than silently carried.
#
# WHAT IT CANNOT SEE — stated rather than glossed
#   It greps for `"update-ref"` argument literals and `mandate_fence::` paths. A ref moved through a
#   helper this script does not know about, through `git push` alone, or by a plumbing command that
#   writes `.git/refs` directly, is invisible to it. It does not parse Rust and cannot tell which
#   function a site sits in, so it cannot prove the fenced site is the one on the write path — only
#   that the counts have not drifted. The honest mitigation is the same as the seams check: the
#   baseline makes *movement* visible even when it cannot attribute it.
#
# USAGE
#   scripts/check-wiki-mutation-fence.sh            # check against the baseline
#   scripts/check-wiki-mutation-fence.sh --update   # regenerate it (then edit the record too)

set -euo pipefail

cd "$(dirname "$0")/.."

BASELINE="scripts/wiki-mutation-fence-baseline.txt"
SCAN_DIR="mycelium-wiki/src"

# The two fence entry points that must keep being reached.
REQUIRED_FENCE_CALLS=(
  "mandate_fence::update_ref_stdin"
  "mandate_fence::push_args"
)

emit_counts() {
  local f
  for f in $(find "$SCAN_DIR" -name '*.rs' | sort); do
    local refs fences
    refs=$(grep -c '"update-ref"' "$f" || true)
    fences=$(grep -c 'mandate_fence::' "$f" || true)
    # Only files that do one or the other are worth a baseline row.
    if [ "$refs" -gt 0 ] || [ "$fences" -gt 0 ]; then
      printf '%s %s %s\n' "$f" "$refs" "$fences"
    fi
  done
}

if [ "${1:-}" = "--update" ]; then
  {
    echo "# Generated by scripts/check-wiki-mutation-fence.sh --update"
    echo "# <file> <ref-moving sites> <mandate_fence:: sites>"
    emit_counts
  } > "$BASELINE"
  echo "Wiki mutation-fence baseline regenerated. Now edit the record that explains it."
  exit 0
fi

if [ ! -f "$BASELINE" ]; then
  echo "Wiki mutation-fence check: no baseline at $BASELINE — run with --update." >&2
  exit 1
fi

fail=0

# 1. The fence entry points must still be reached at all.
for call in "${REQUIRED_FENCE_CALLS[@]}"; do
  if ! grep -rq "$call" "$SCAN_DIR"; then
    echo "FAIL: the fence entry point '$call' is no longer called anywhere in $SCAN_DIR." >&2
    echo "      scoped-mandates.md §5 puts the mandate check inside the store's atomic boundary;" >&2
    echo "      with this call gone, it is not there." >&2
    fail=1
  fi
done

# 2. Counts must not drift.
current=$(mktemp)
trap 'rm -f "$current"' EXIT
emit_counts > "$current"

while read -r file base_refs base_fences; do
  case "$file" in '#'*|'') continue ;; esac
  cur_line=$(grep "^$file " "$current" || true)
  if [ -z "$cur_line" ]; then
    echo "NOTE: $file no longer has ref-moving or fence sites (was $base_refs/$base_fences)." >&2
    echo "      If that is deliberate, regenerate the baseline." >&2
    fail=1
    continue
  fi
  cur_refs=$(echo "$cur_line" | cut -d' ' -f2)
  cur_fences=$(echo "$cur_line" | cut -d' ' -f3)

  if [ "$cur_fences" -lt "$base_fences" ]; then
    echo "FAIL: $file lost a mandate fence site ($base_fences -> $cur_fences)." >&2
    echo "      A write path that was inside the mandate's atomic boundary has left it." >&2
    fail=1
  fi
  if [ "$cur_refs" -gt "$base_refs" ] && [ "$cur_fences" -le "$base_fences" ]; then
    echo "FAIL: $file gained a ref-moving site ($base_refs -> $cur_refs) with no new fence." >&2
    echo "      v3-contracts-axis.md §6.3 claims every mutation path is protected. A new" >&2
    echo "      'update-ref' beside the fenced one is how that claim stops being true." >&2
    echo "      Either route it through mandate_fence::, or record why it is exempt in" >&2
    echo "      docs/design/scoped-mandates.md §7.2 and regenerate the baseline." >&2
    fail=1
  fi
  if [ "$cur_refs" -lt "$base_refs" ]; then
    echo "note: $file lost a ref-moving site ($base_refs -> $cur_refs) — progress; regenerate the baseline." >&2
  fi
done < "$BASELINE"

# 3. A file that is new to the scan and moves refs without fencing them.
while read -r file cur_refs cur_fences; do
  if ! grep -q "^$file " "$BASELINE"; then
    if [ "$cur_refs" -gt 0 ] && [ "$cur_fences" -eq 0 ]; then
      echo "FAIL: $file is new and moves git refs ($cur_refs sites) with no mandate fence." >&2
      fail=1
    else
      echo "note: $file is new to the scan ($cur_refs ref sites, $cur_fences fence sites) — regenerate the baseline." >&2
    fi
  fi
done < "$current"

if [ "$fail" -ne 0 ]; then
  exit 1
fi

echo "Wiki mutation-fence check: clean."
