//! The substrate's own decision points, described (plan I1) — catalogue-only entries for propagation,
//! admission, matching, membership and the authority gates. Metadata only (`mycelium_core::rule`).

use mycelium_core::rule::{Guard, Input, Outcome, OutcomeKind::*, Responsibility::*, RuleDescriptor, TracePolicy::*};

const STORE: Input = Input { source: "the LWW store and its HLC", scope: "this node", freshness: "local, atomic" };
const FRAME: Input = Input { source: "an incoming wire frame", scope: "one peer connection", freshness: "as received" };

pub static RULES: &[RuleDescriptor] = &[
    RuleDescriptor {
        id: "kv.propagation", revision: 1, subsystem: "mycelium-core::store / connection", responsibilities: &[Propagation],
        trigger: "a local write, an incoming update, an anti-entropy round",
        inputs: &[STORE, FRAME],
        outcomes: &[Outcome { kind: Action, reasons: &["applied_newer", "forwarded"] }, Outcome { kind: NoAction, reasons: &["older_or_equal", "seen"] }, Outcome { kind: Refusal, reasons: &["frame_too_large", "signature_invalid", "sender_removed"] }],
        effects: &["the store (LWW by HLC), the WAL after it, the gossip shards"],
        guards: &[Guard::Provenance], may_trigger: &["signal.admission"], may_inhibit: &[], depends_on: &[],
        symbol: "store::apply_and_notify / connection::handle_connection", docs: "docs/guide/01-gossip-kv.md",
        tests: &["gossip_spreads_membership_for_discovery", "codec_matches_golden_wire_bytes"], trace: CatalogueOnly,
        summary: "Every update converges by last-writer-wins on the HLC; propagation is unconditional and never taught a higher-layer law (detection, not prevention).",
    },
    RuleDescriptor {
        id: "kv.expiry", revision: 1, subsystem: "mycelium-core::store", responsibilities: &[Propagation],
        trigger: "the GC tick, and every read",
        inputs: &[STORE, Input { source: "the entry's TTL and the wall clock through the seam", scope: "this node", freshness: "the decision clock" }],
        outcomes: &[Outcome { kind: Action, reasons: &["expired"] }, Outcome { kind: NoAction, reasons: &["live", "no_ttl"] }],
        effects: &["the entry removed; a tombstone where the writer deleted"],
        guards: &[], may_trigger: &["prov.presence_floor"], may_inhibit: &[], depends_on: &[],
        symbol: "store::Store::flush_expired", docs: "docs/guide/01-gossip-kv.md",
        tests: &["flush_expired", "is_expired", "default_ttl_secs"], trace: CatalogueOnly,
        summary: "An advertisement its writer stopped refreshing leaves the view after its TTL; a stale view is possible in between.",
    },
    RuleDescriptor {
        id: "signal.admission", revision: 1, subsystem: "mycelium-core::signal", responsibilities: &[Admission],
        trigger: "a signal arriving at this node, local or forwarded",
        inputs: &[Input { source: "the signal's scope and this node's boundary groups (`grp/`)", scope: "this node", freshness: "local" }, Input { source: "the gossip shards' fill and the handlers' fill", scope: "this node", freshness: "sampled" }],
        outcomes: &[Outcome { kind: Action, reasons: &["admitted"] }, Outcome { kind: Refusal, reasons: &["scope_not_admitted"] }, Outcome { kind: Deferral, reasons: &["shed_under_load"] }],
        effects: &["delivery to local handlers; the sender log"],
        guards: &[Guard::Other], may_trigger: &["signal.suppression"], may_inhibit: &[], depends_on: &["signal.forwarding"],
        symbol: "ops::deliver_locally", docs: "docs/guide/03-signals.md",
        tests: &["individual_scope_bypasses_opacity", "boundary_transition_signals_are_never_locally_shed", "test_group_quorum_excludes_ex_member"], trace: Partial("refusals and sheds only; an admitted signal is the hot path and records nothing"),
        summary: "Admission is scoped (Cluster · Group · Individual) and shed under load — except Individual and the boundary transitions; shedding happens before the sender is recorded.",
    },
    RuleDescriptor {
        id: "signal.forwarding", revision: 1, subsystem: "mycelium-core::ops", responsibilities: &[Propagation],
        trigger: "a signal emitted or received with TTL left",
        inputs: &[FRAME],
        outcomes: &[Outcome { kind: Action, reasons: &["forwarded"] }, Outcome { kind: NoAction, reasons: &["ttl_exhausted", "terminates_here", "seen"] }],
        effects: &["the gossip shards"],
        guards: &[], may_trigger: &["signal.admission"], may_inhibit: &[], depends_on: &[],
        symbol: "ops::emit_signal / forward_hint", docs: "docs/wiki/dev/architecture/runtime-invariants.md",
        tests: &["forwarding_is_unconditional_through_non_member_relay"], trace: CatalogueOnly,
        summary: "Forwarding is unconditional (flood fallback); only admission is scoped, and a frame addressed to this node terminates here.",
    },
    RuleDescriptor {
        id: "signal.suppression", revision: 1, subsystem: "mycelium-core::signal", responsibilities: &[Admission],
        trigger: "an admitted signal of a suppressed kind",
        inputs: &[Input { source: "the suppression table", scope: "this node", freshness: "local" }],
        outcomes: &[Outcome { kind: Deferral, reasons: &["suppressed_until"] }, Outcome { kind: Action, reasons: &["delivered", "released_on_flush"] }],
        effects: &["held signals delivered on flush"],
        guards: &[Guard::Cooldown], may_trigger: &[], may_inhibit: &[], depends_on: &["signal.admission"],
        symbol: "signal::SignalHandlers::deliver / flush_expired", docs: "docs/guide/03-signals.md",
        tests: &["is_suppressed", "is_suppressed_at", "flush_expired_delivers_held_signals"], trace: CatalogueOnly,
        summary: "A kind can be held until a time; held signals are released on flush. Suppression never changes forwarding.",
    },
    RuleDescriptor {
        id: "cap.match", revision: 1, subsystem: "mycelium::capability", responsibilities: &[Response],
        trigger: "a resolve, a demand, the offline check, a group filter",
        inputs: &[Input { source: "`cap/` advertisements as gossiped", scope: "the fleet as this node sees it", freshness: "as gossiped; TTL-bounded" }],
        outcomes: &[Outcome { kind: Action, reasons: &["matched"] }, Outcome { kind: NoAction, reasons: &["ns_or_name_differs", "schema_id_differs", "constraint_unmet", "opaque_skipped"] }],
        effects: &[], guards: &[], may_trigger: &["prov.demand_response"], may_inhibit: &[], depends_on: &["kv.propagation"],
        symbol: "capability::CapFilter::matches", docs: "docs/guide/02-capabilities.md",
        tests: &["filter_matches_capability", "constraint_matches_eq_ne", "constraint_matches_ordering"], trace: CatalogueOnly,
        summary: "The one matching rule, shared by the resolver and the offline check: namespace, name, schema id, typed attribute constraints; opacity skips, it does not unmatch.",
    },
    RuleDescriptor {
        id: "membership.governed", revision: 1, subsystem: "mycelium::membership_governor", responsibilities: &[Response],
        trigger: "the governor tick",
        inputs: &[Input { source: "the governed group's roster and floor (`grp/`, `sys/`)", scope: "the group as this node sees it", freshness: "as gossiped; the confidence bound applies" }, Input { source: "ViewConfidence (peers heard, staleness)", scope: "this node", freshness: "computed at the tick" }],
        outcomes: &[Outcome { kind: Action, reasons: &["join", "leave"] }, Outcome { kind: Deferral, reasons: &["view_not_confident", "settling", "spacing"] }, Outcome { kind: NoAction, reasons: &["hold"] }],
        effects: &["this node joins or leaves the group (`grp/`); the control ledger"],
        guards: &[Guard::Settling, Guard::Cooldown], may_trigger: &["prov.presence_floor"], may_inhibit: &[], depends_on: &["kv.propagation"],
        symbol: "agent::membership_governor", docs: "docs/guide/22-stability-and-control.md",
        tests: &["a_membership_decision_classifies_by_cost_not_by_verb", "a_stale_membership_intent_stops_declaring_a_floor", "healthy_membership_in_bounds_does_not_trip"], trace: Instrumented,
        summary: "This node rolls to join or leave a governed group against the intent's band — after spacing and settling, and (under an enforcing profile) only on a confident view.",
    },
    RuleDescriptor {
        id: "gateway.auth", revision: 1, subsystem: "mycelium::agent::http", responsibilities: &[Authority],
        trigger: "every gateway request",
        inputs: &[Input { source: "the bearer or JWT presented, the token tables, `[oidc]`", scope: "this node", freshness: "local" }],
        outcomes: &[Outcome { kind: Action, reasons: &["admitted", "anonymous_open_gateway"] }, Outcome { kind: Refusal, reasons: &["authentication_required", "insufficient_scope"] }],
        effects: &["the resolved principal and granted scopes travel to the handler"],
        guards: &[Guard::Authority], may_trigger: &["ae.preflight"], may_inhibit: &[], depends_on: &[],
        symbol: "http::gateway_auth / required_scope", docs: "docs/operations/rbac.md",
        tests: &["named_tokens_alone_still_close_the_gateway", "a_token_table_this_build_cannot_enforce_refuses_to_start", "an_exposed_gateway_with_no_credential_refuses_to_start"], trace: CatalogueOnly,
        summary: "Deny by default under `compliance`: a route needs its scope; with no credential model the gateway is open — on loopback only, since a non-loopback one refuses to start unless `gateway_allow_unauthenticated` waives it — and a table the build cannot enforce refuses to start.",
    },
    RuleDescriptor {
        id: "ae.preflight", revision: 1, subsystem: "mycelium::agent::http", responsibilities: &[Authority],
        trigger: "a gateway dispatch that an evaluator covers",
        inputs: &[Input { source: "the action envelope, the presented mandate, the deployed policy revision", scope: "this request", freshness: "the decision clock" }],
        outcomes: &[Outcome { kind: Action, reasons: &["permit"] }, Outcome { kind: Refusal, reasons: &["deny", "indeterminate", "mandate_revoked", "mandate_expired", "stale_policy"] }, Outcome { kind: NoAction, reasons: &["inert_no_evaluator"] }],
        effects: &["the evidence journal record before dispatch; the audit chain reference under `compliance`"],
        guards: &[Guard::Authority], may_trigger: &[], may_inhibit: &[], depends_on: &["gateway.auth"],
        symbol: "http::ae_preflight / ae_record", docs: "docs/guide/20-authorising-actions.md",
        tests: &["an_expired_envelope_is_denied_before_the_evaluator_runs", "test_c7_the_bypass_matrix_no_door_runs_revoked_work"], trace: CatalogueOnly,
        summary: "Permit, deny or indeterminate, recorded before the work runs; a refused mandate denies before policy runs, so a policy engine cannot launder a revocation.",
    },
    RuleDescriptor {
        id: "provider.enforcement", revision: 1, subsystem: "mycelium::agent::provider_enforcement", responsibilities: &[Authority],
        trigger: "a protected RPC kind arriving at a provider with enforcement on",
        inputs: &[Input { source: "the node's evaluator and execution authority; the carried mandate", scope: "this node", freshness: "the decision clock" }],
        outcomes: &[Outcome { kind: Action, reasons: &["permit"] }, Outcome { kind: Refusal, reasons: &["deny", "no_evaluator", "at_capacity"] }, Outcome { kind: NoAction, reasons: &["enforcement_off"] }],
        effects: &["the evidence journal; the handler never runs on a refusal"],
        guards: &[Guard::Authority, Guard::ResourceBudget], may_trigger: &[], may_inhibit: &[], depends_on: &[],
        symbol: "provider_enforcement::check", docs: "docs/guide/20-authorising-actions.md",
        tests: &["test_c7_the_bypass_matrix_no_door_runs_revoked_work"], trace: CatalogueOnly,
        summary: "Authority where the work happens: a protected call is checked at the provider whichever door it came through; with enforcement on and no evaluator it is refused, with it off nothing is checked.",
    },
    RuleDescriptor {
        id: "a2a.admission", revision: 1, subsystem: "mycelium::agent::a2a", responsibilities: &[Admission, Authority],
        trigger: "a request on `/a2a`",
        inputs: &[Input { source: "an optional bearer or federation credential", scope: "this request", freshness: "local" }],
        outcomes: &[Outcome { kind: Action, reasons: &["identified", "anonymous"] }, Outcome { kind: Refusal, reasons: &["credential_invalid"] }],
        effects: &["a principal whose scopes are dropped; the AE preflight decides the rest"],
        guards: &[], may_trigger: &["ae.preflight"], may_inhibit: &[], depends_on: &[],
        symbol: "http::a2a_optional_auth", docs: "docs/operations/production-readiness.md",
        tests: &["a2a_is_anonymous_dispatch_whatever_bearer_is_configured"], trace: CatalogueOnly,
        summary: "An absent credential is anonymous and a present bearer's scopes are dropped: a bearer does not gate this route, an evaluator does.",
    },
];
